import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { CaseImage } from "@/components/CaseImage";

const asset = (name: string) => `/images/premier-bays/${name}`;

function Visual({ src, alt, className = "" }: { src: string; alt: string; className?: string }) {
  return <div className={`pbVisual ${className}`}><CaseImage src={asset(src)} alt={alt} /></div>;
}

export function PremierBaysCaseStudy() {
  return <main className="premierBaysCaseStudy">
    <Header />
    <section className="pbHero"><div><h1>Premier Bays</h1><p>Bringing annual parking into the PayByPhone app for UK motorists.</p><div className="pbMeta"><strong>PayByPhone · 2020</strong><span>Product Design · UX Research · Interaction Design</span></div></div><Visual src="hero-figma-source-1.png" alt="Premier Bays annual-parking experience" className="pbHeroVisual" /></section>
    <section className="pbSection pbChallenge"><div className="pbCopy"><h2>Challenge</h2><h3>A missing feature was keeping a legacy platform alive.</h3><p>PayByPhone had acquired Dash, a UK parking platform that was costly to maintain. Premier Bays, typically an annual parking ticket for a specific space, was the remaining functionality that couldn&apos;t be handled in the PayByPhone app. The business needed to migrate the experience while maintaining its strategic partnership with NCP.</p><div className="pbPoints"><div><strong>Reduce costs</strong><span>Retire reliance on the legacy Dash platform</span></div><div><strong>Maintain partnership</strong><span>Support NCP&apos;s Premier Bays offering</span></div></div></div><Visual src="challenge-ui-1.png" alt="Legacy Dash Premier Bays booking interface" className="pbChallengeVisual" /></section>
    <section className="pbSection pbGoal"><div className="pbCopy"><h2>Goal</h2><h3>Bring annual parking into PayByPhone without losing existing usage.</h3><div className="pbMetrics"><div><span>BUSINESS</span><strong>200</strong><em>transactions per year</em></div><div><span>USER</span><strong>68+</strong><em>SUS score</em></div><div><span>&nbsp;</span><strong>78%+</strong><em>task success</em></div></div></div></section>
    <section className="pbSection pbResearch"><div className="pbCopy"><h2>Annual parking worked differently from everyday parking.</h2><p>Through research, I looked at how motorists understood and accessed Premier Bays, including the terminology they expected and how they would manage an annual ticket.</p><div className="pbPoints"><div><strong>Consistency</strong><span>Align terminology across parking signs and digital experiences.</span></div><div><strong>Reduce steps</strong><span>Make annual parking easier to find and renew.</span></div><div><strong>Easy to use</strong><span>Let motorists purchase and manage their ticket without leaving the app.</span></div></div></div><div className="pbResearchVisuals"><Visual src="research-ui-2.png" alt="Legacy annual-parking location selection" /><Visual src="research-ui-1.png" alt="Legacy annual-parking booking form" /></div></section>
    <section className="pbSection pbExperience"><div className="pbWideCopy"><h2>One experience to purchase and manage annual parking.</h2><p>I designed the core Premier Bays experience around four key tasks:</p><ul><li>Purchase an annual ticket</li><li>View an active ticket</li><li>Manage assigned vehicles</li><li>Renew an annual ticket</li></ul><p>The purchase flow brought location search, bay selection, vehicle selection, payment, and ticket details into the existing PayByPhone experience.</p></div><Visual src="experience-flow.png" alt="Premier Bays purchase and ticket-management screens" className="pbExperienceVisual" /></section>
    <section className="pbSection pbTesting"><div className="pbWideCopy"><h2>Testing surfaced an expectation to manage vehicles.</h2><p>During usability testing, participants initially struggled to find where they could edit vehicles, and most expected to add or remove vehicles directly from their annual ticket.</p><div className="pbTestingGrid"><div><strong>FINDING</strong><em>“Where do I edit my vehicles?”</em></div><div><strong>EXPLORATION</strong><em>Manage vehicles directly from the annual ticket</em></div><div><strong>DECISION</strong><em>Deprioritize for launch based on effort vs. value</em></div></div></div><div className="pbTestingPhones"><CaseImage src="/images/premier-bays/testing-finding.png" alt="Testing finding: vehicle management discoverability" /><CaseImage src="/images/premier-bays/testing-exploration.png" alt="Testing exploration: manage vehicles from annual ticket" /><CaseImage src="/images/premier-bays/testing-decision.png" alt="Testing decision: vehicle editing flow" /></div></section>
    <section className="pbSection pbImpact"><div className="pbWideCopy"><h2>Annual parking, now inside PayByPhone.</h2><p>Motorists could purchase and manage an annual ticket for a specific parking space directly in the app, bringing Premier Bays into the core PayByPhone experience.</p><div className="pbMetrics pbImpactMetrics"><div><span>BUSINESS</span><strong>212</strong><em>Premier Bay transactions<br />Target: 200+</em></div><div><span>&nbsp;</span><strong>+12%</strong><em>YoY transactions</em></div><div><span>USER</span><strong>91</strong><em>SUS score<br />Target: 68+</em></div><div><span>&nbsp;</span><strong>94%</strong><em>task success<br />Target: 78+</em></div></div><small>Data from Nov 2020 - Nov 2021</small></div><Visual src="hero-ui-1.png" alt="Premier Bays results and operations experience" className="pbImpactVisual" /></section>
    <section className="premierBaysNext">
      <a href="/work/developer-center" aria-label="View the Developer Center case study">
        <img src={asset("next-project.png")} alt="Next project: Developer Center" />
      </a>
    </section>
    <Footer />
  </main>;
}
